# We compile on pull requests, no need to do branches.
branches:
  only:
  - master

language: java

jdk:
- oraclejdk8


script: gradle :buildPlugin

# Travis sometimes fails to download deps from repo1.maven.org
# A cache avoids downloading too much, and will also speed up the build.
# NB: There is one cache per branch and language version/ compiler version/ JDK version
cache:
  # The timeout (in seconds) empties the cache to avoid being stuck with a corrupted artefact
  timeout: 86400  # 24 hours
  directories:
  - $HOME/.m2
