/* The following code was generated by JFlex 1.4.1 on 11.07.07 3:44 */

package org.intellij.lang.jflex.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import org.intellij.lang.jflex.JFlexElementTypes;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 11.07.07 3:44 from the specification file
 * <tt>C:/Documents and Settings/aefimov/Projects/idea/experimental/jflex/src/org/intellij/lang/jflex/lexer/JFlex.flex</tt>
 */
final class _JFlexLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int OPTION = 8;
  public static final int OPT_PARAMS = 11;
  public static final int ACTION_REGEXP_CLASS = 20;
  public static final int IDENTIFIER = 3;
  public static final int OPT_JAVA_CODE = 13;
  public static final int OPT_ERROR = 9;
  public static final int OPT_CODE = 12;
  public static final int IDENTIFIER_REGEXP_LITERAL = 4;
  public static final int IDENTIFIER_REGEXP_CLASS = 7;
  public static final int IDENTIFIER_REGEXP_IDENTIFIER = 6;
  public static final int RULE = 17;
  public static final int OPT_EXCEPTION = 14;
  public static final int ACTION = 21;
  public static final int ACTION_REGEXP = 18;
  public static final int IDENTIFIER_REGEXP = 5;
  public static final int ACTION_JAVA_CODE = 22;
  public static final int STATE = 16;
  public static final int LEXICAL_RULES = 2;
  public static final int ACTION_REGEXP_IDENTIFIER = 19;
  public static final int YYINITIAL = 0;
  public static final int OPTIONS_AND_DECLARATIONS = 1;
  public static final int OPT_BOOLEAN = 15;
  public static final int OPT_PARAM = 10;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\24\1\4\1\3\1\0\1\5\1\2\16\24\4\0\1\4\1\27"+
    "\1\26\1\0\1\23\1\1\2\0\1\35\1\36\1\10\1\30\1\63"+
    "\2\0\1\7\1\24\1\61\4\24\1\62\1\57\1\60\1\24\2\0"+
    "\1\31\1\32\1\64\1\30\1\0\32\23\1\33\1\6\1\37\1\0"+
    "\1\23\1\0\1\21\1\47\1\40\1\45\1\15\1\17\1\54\1\51"+
    "\1\12\1\23\1\56\1\22\1\42\1\13\1\16\1\43\1\23\1\50"+
    "\1\41\1\14\1\46\1\20\1\52\1\44\1\55\1\53\1\25\1\34"+
    "\1\11\1\27\41\24\2\0\4\23\4\0\1\23\2\0\1\24\7\0"+
    "\1\23\4\0\1\23\5\0\27\23\1\0\37\23\1\0\u013f\23\31\0"+
    "\162\23\4\0\14\23\16\0\5\23\11\0\1\23\21\0\130\24\5\0"+
    "\23\24\12\0\1\23\13\0\1\23\1\0\3\23\1\0\1\23\1\0"+
    "\24\23\1\0\54\23\1\0\46\23\1\0\5\23\4\0\202\23\1\0"+
    "\4\24\3\0\105\23\1\0\46\23\2\0\2\23\6\0\20\23\41\0"+
    "\46\23\2\0\1\23\7\0\47\23\11\0\21\24\1\0\27\24\1\0"+
    "\3\24\1\0\1\24\1\0\2\24\1\0\1\24\13\0\33\23\5\0"+
    "\3\23\15\0\4\24\14\0\6\24\13\0\32\23\5\0\13\23\16\24"+
    "\7\0\12\24\4\0\2\23\1\24\143\23\1\0\1\23\10\24\1\0"+
    "\6\24\2\23\2\24\1\0\4\24\2\23\12\24\3\23\2\0\1\23"+
    "\17\0\1\24\1\23\1\24\36\23\33\24\2\0\3\23\60\0\46\23"+
    "\13\24\1\23\u014f\0\3\24\66\23\2\0\1\24\1\23\20\24\2\0"+
    "\1\23\4\24\3\0\12\23\2\24\2\0\12\24\21\0\3\24\1\0"+
    "\10\23\2\0\2\23\2\0\26\23\1\0\7\23\1\0\1\23\3\0"+
    "\4\23\2\0\1\24\1\23\7\24\2\0\2\24\2\0\3\24\11\0"+
    "\1\24\4\0\2\23\1\0\3\23\2\24\2\0\12\24\4\23\15\0"+
    "\3\24\1\0\6\23\4\0\2\23\2\0\26\23\1\0\7\23\1\0"+
    "\2\23\1\0\2\23\1\0\2\23\2\0\1\24\1\0\5\24\4\0"+
    "\2\24\2\0\3\24\13\0\4\23\1\0\1\23\7\0\14\24\3\23"+
    "\14\0\3\24\1\0\11\23\1\0\3\23\1\0\26\23\1\0\7\23"+
    "\1\0\2\23\1\0\5\23\2\0\1\24\1\23\10\24\1\0\3\24"+
    "\1\0\3\24\2\0\1\23\17\0\2\23\2\24\2\0\12\24\1\0"+
    "\1\23\17\0\3\24\1\0\10\23\2\0\2\23\2\0\26\23\1\0"+
    "\7\23\1\0\2\23\1\0\5\23\2\0\1\24\1\23\6\24\3\0"+
    "\2\24\2\0\3\24\10\0\2\24\4\0\2\23\1\0\3\23\4\0"+
    "\12\24\1\0\1\23\20\0\1\24\1\23\1\0\6\23\3\0\3\23"+
    "\1\0\4\23\3\0\2\23\1\0\1\23\1\0\2\23\3\0\2\23"+
    "\3\0\3\23\3\0\10\23\1\0\3\23\4\0\5\24\3\0\3\24"+
    "\1\0\4\24\11\0\1\24\17\0\11\24\11\0\1\23\7\0\3\24"+
    "\1\0\10\23\1\0\3\23\1\0\27\23\1\0\12\23\1\0\5\23"+
    "\4\0\7\24\1\0\3\24\1\0\4\24\7\0\2\24\11\0\2\23"+
    "\4\0\12\24\22\0\2\24\1\0\10\23\1\0\3\23\1\0\27\23"+
    "\1\0\12\23\1\0\5\23\2\0\1\24\1\23\7\24\1\0\3\24"+
    "\1\0\4\24\7\0\2\24\7\0\1\23\1\0\2\23\4\0\12\24"+
    "\22\0\2\24\1\0\10\23\1\0\3\23\1\0\27\23\1\0\20\23"+
    "\4\0\6\24\2\0\3\24\1\0\4\24\11\0\1\24\10\0\2\23"+
    "\4\0\12\24\22\0\2\24\1\0\22\23\3\0\30\23\1\0\11\23"+
    "\1\0\1\23\2\0\7\23\3\0\1\24\4\0\6\24\1\0\1\24"+
    "\1\0\10\24\22\0\2\24\15\0\60\23\1\24\2\23\7\24\4\0"+
    "\10\23\10\24\1\0\12\24\47\0\2\23\1\0\1\23\2\0\2\23"+
    "\1\0\1\23\2\0\1\23\6\0\4\23\1\0\7\23\1\0\3\23"+
    "\1\0\1\23\1\0\1\23\2\0\2\23\1\0\4\23\1\24\2\23"+
    "\6\24\1\0\2\24\1\23\2\0\5\23\1\0\1\23\1\0\6\24"+
    "\2\0\12\24\2\0\2\23\42\0\1\23\27\0\2\24\6\0\12\24"+
    "\13\0\1\24\1\0\1\24\1\0\1\24\4\0\2\24\10\23\1\0"+
    "\42\23\6\0\24\24\1\0\2\24\4\23\4\0\10\24\1\0\44\24"+
    "\11\0\1\24\71\0\42\23\1\0\5\23\1\0\2\23\1\0\7\24"+
    "\3\0\4\24\6\0\12\24\6\0\6\23\4\24\106\0\46\23\12\0"+
    "\51\23\7\0\132\23\5\0\104\23\5\0\122\23\6\0\7\23\1\0"+
    "\77\23\1\0\1\23\1\0\4\23\2\0\7\23\1\0\1\23\1\0"+
    "\4\23\2\0\47\23\1\0\1\23\1\0\4\23\2\0\37\23\1\0"+
    "\1\23\1\0\4\23\2\0\7\23\1\0\1\23\1\0\4\23\2\0"+
    "\7\23\1\0\7\23\1\0\27\23\1\0\37\23\1\0\1\23\1\0"+
    "\4\23\2\0\7\23\1\0\47\23\1\0\23\23\16\0\11\24\56\0"+
    "\125\23\14\0\u026c\23\2\0\10\23\12\0\32\23\5\0\113\23\3\0"+
    "\3\23\17\0\15\23\1\0\4\23\3\24\13\0\22\23\3\24\13\0"+
    "\22\23\2\24\14\0\15\23\1\0\3\23\1\0\2\24\14\0\64\23"+
    "\40\24\3\0\1\23\3\0\2\23\1\24\2\0\12\24\41\0\3\24"+
    "\2\0\12\24\6\0\130\23\10\0\51\23\1\24\126\0\35\23\3\0"+
    "\14\24\4\0\14\24\12\0\12\24\36\23\2\0\5\23\u038b\0\154\23"+
    "\224\0\234\23\4\0\132\23\6\0\26\23\2\0\6\23\2\0\46\23"+
    "\2\0\6\23\2\0\10\23\1\0\1\23\1\0\1\23\1\0\1\23"+
    "\1\0\37\23\2\0\65\23\1\0\7\23\1\0\1\23\3\0\3\23"+
    "\1\0\7\23\3\0\4\23\2\0\6\23\4\0\15\23\5\0\3\23"+
    "\1\0\7\23\17\0\4\24\32\0\5\24\20\0\2\23\23\0\1\23"+
    "\13\0\4\24\6\0\6\24\1\0\1\23\15\0\1\23\40\0\22\23"+
    "\36\0\15\24\4\0\1\24\3\0\6\24\27\0\1\23\4\0\1\23"+
    "\2\0\12\23\1\0\1\23\3\0\5\23\6\0\1\23\1\0\1\23"+
    "\1\0\1\23\1\0\4\23\1\0\3\23\1\0\7\23\3\0\3\23"+
    "\5\0\5\23\26\0\44\23\u0e81\0\3\23\31\0\11\23\6\24\1\0"+
    "\5\23\2\0\5\23\4\0\126\23\2\0\2\24\2\0\3\23\1\0"+
    "\137\23\5\0\50\23\4\0\136\23\21\0\30\23\70\0\20\23\u0200\0"+
    "\u19b6\23\112\0\u51a6\23\132\0\u048d\23\u0773\0\u2ba4\23\u215c\0\u012e\23\2\0"+
    "\73\23\225\0\7\23\14\0\5\23\5\0\1\23\1\24\12\23\1\0"+
    "\15\23\1\0\5\23\1\0\1\23\1\0\2\23\1\0\2\23\1\0"+
    "\154\23\41\0\u016b\23\22\0\100\23\2\0\66\23\50\0\15\23\3\0"+
    "\20\24\20\0\4\24\17\0\2\23\30\0\3\23\31\0\1\23\6\0"+
    "\5\23\1\0\207\23\2\0\1\24\4\0\1\23\13\0\12\24\7\0"+
    "\32\23\4\0\1\23\1\0\32\23\12\0\132\23\3\0\6\23\2\0"+
    "\6\23\2\0\6\23\2\0\3\23\3\0\2\23\3\0\2\23\22\0"+
    "\3\24\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\27\0\3\1\1\2\1\3\2\4\1\2\1\5\1\6"+
    "\2\7\1\6\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\4\1\16\1\15\1\17\1\20\1\15\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\3\31\1\32"+
    "\1\33\1\34\1\35\7\33\1\36\1\33\1\37\1\33"+
    "\1\40\7\33\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\3\52\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\61\1\62\2\61\1\63\1\7\1\64"+
    "\1\65\1\66\1\67\2\70\1\6\1\71\1\72\1\73"+
    "\1\74\1\75\1\74\1\76\1\77\1\74\1\100\1\101"+
    "\1\102\1\103\1\104\1\105\1\106\1\107\1\110\3\111"+
    "\1\112\1\113\1\114\1\77\2\115\1\116\1\117\1\120"+
    "\1\121\1\0\1\122\2\0\1\123\3\0\1\124\2\0"+
    "\1\125\40\0\1\126\5\0\1\127\5\0\1\130\2\0"+
    "\1\131\4\0\1\124\1\125\1\0\1\132\6\0\1\133"+
    "\12\0\1\134\26\0\1\135\1\130\1\131\1\0\1\122"+
    "\1\0\1\123\1\136\7\0\1\137\6\0\1\140\2\0"+
    "\1\141\5\0\1\142\4\0\1\143\10\0\1\144\1\145"+
    "\3\0\1\146\2\0\1\127\1\122\1\123\7\0\1\147"+
    "\4\0\1\150\5\0\1\151\3\0\1\152\4\0\1\153"+
    "\2\0\1\154\1\155\1\0\1\156\2\0\1\157\1\127"+
    "\10\0\1\160\5\0\1\161\1\0\1\162\3\0\1\163"+
    "\1\164\1\165\5\0\1\166\1\167\1\170\2\0\1\171"+
    "\2\0\1\172\7\0\1\173\5\0\1\174\1\175\1\176"+
    "\1\0\1\177\1\200\1\201\4\0\1\202\4\0\1\203"+
    "\2\0\1\204\1\205\1\206\1\207\1\210\1\211";

  private static int [] zzUnpackAction() {
    int [] result = new int[421];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\u0109\0\u013e\0\u0173"+
    "\0\u01a8\0\u01dd\0\u0212\0\u0247\0\u027c\0\u02b1\0\u02e6\0\u031b"+
    "\0\u0350\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459\0\u048e\0\u04c3"+
    "\0\u04f8\0\u052d\0\u04c3\0\u0562\0\u0597\0\u05cc\0\u0601\0\u0636"+
    "\0\u04c3\0\u066b\0\u06a0\0\u06d5\0\u04c3\0\u070a\0\u04c3\0\u04c3"+
    "\0\u073f\0\u04c3\0\u0774\0\u07a9\0\u07de\0\u04c3\0\u04c3\0\u0813"+
    "\0\u04c3\0\u04c3\0\u04c3\0\u04c3\0\u04c3\0\u04c3\0\u04c3\0\u0848"+
    "\0\u04c3\0\u087d\0\u08b2\0\u04c3\0\u04c3\0\u08e7\0\u04c3\0\u091c"+
    "\0\u0951\0\u0986\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u04c3\0\u0a8f"+
    "\0\u0ac4\0\u0af9\0\u0b2e\0\u0b63\0\u0b98\0\u0bcd\0\u0c02\0\u0c37"+
    "\0\u0c6c\0\u0ca1\0\u04c3\0\u0cd6\0\u0d0b\0\u04c3\0\u0d40\0\u0d75"+
    "\0\u04c3\0\u04c3\0\u04c3\0\u04c3\0\u0daa\0\u0ddf\0\u04c3\0\u0e14"+
    "\0\u04c3\0\u0e49\0\u04c3\0\u04c3\0\u04c3\0\u0e7e\0\u0eb3\0\u0ee8"+
    "\0\u04c3\0\u0f1d\0\u0f52\0\u0f87\0\u04c3\0\u04c3\0\u0fbc\0\u0ff1"+
    "\0\u1026\0\u04c3\0\u105b\0\u04c3\0\u04c3\0\u1090\0\u10c5\0\u04c3"+
    "\0\u10fa\0\u112f\0\u04c3\0\u04c3\0\u04c3\0\u04c3\0\u04c3\0\u04c3"+
    "\0\u04c3\0\u1164\0\u04c3\0\u04c3\0\u1199\0\u11ce\0\u04c3\0\u04c3"+
    "\0\u1203\0\u04c3\0\u04c3\0\u1238\0\u04c3\0\u04c3\0\u04c3\0\u04c3"+
    "\0\u126d\0\u12a2\0\u12d7\0\u130c\0\u1341\0\u1376\0\u0813\0\u13ab"+
    "\0\u04c3\0\u08b2\0\u13e0\0\u04c3\0\u1415\0\u144a\0\u147f\0\u14b4"+
    "\0\u14e9\0\u151e\0\u1553\0\u1588\0\u15bd\0\u15f2\0\u1627\0\u165c"+
    "\0\u1691\0\u16c6\0\u16fb\0\u1730\0\u1765\0\u179a\0\u17cf\0\u1804"+
    "\0\u1839\0\u186e\0\u18a3\0\u18d8\0\u190d\0\u1942\0\u1977\0\u19ac"+
    "\0\u19e1\0\u1a16\0\u1a4b\0\u1a80\0\u04c3\0\u1ab5\0\u1aea\0\u1b1f"+
    "\0\u1b54\0\u1b89\0\u1bbe\0\u1bf3\0\u1c28\0\u1c5d\0\u112f\0\u1c92"+
    "\0\u04c3\0\u11ce\0\u1cc7\0\u04c3\0\u1cfc\0\u1d31\0\u1d66\0\u1d9b"+
    "\0\u0813\0\u08b2\0\u1dd0\0\u1e05\0\u1e3a\0\u1e6f\0\u1ea4\0\u1ed9"+
    "\0\u1f0e\0\u1f43\0\u1f78\0\u1fad\0\u1fe2\0\u2017\0\u204c\0\u2081"+
    "\0\u20b6\0\u20eb\0\u2120\0\u2155\0\u218a\0\u21bf\0\u21f4\0\u2229"+
    "\0\u225e\0\u2293\0\u22c8\0\u22fd\0\u2332\0\u2367\0\u239c\0\u23d1"+
    "\0\u2406\0\u243b\0\u2470\0\u24a5\0\u24da\0\u250f\0\u2544\0\u2579"+
    "\0\u25ae\0\u25e3\0\u2618\0\u264d\0\u04c3\0\u112f\0\u11ce\0\u2682"+
    "\0\u1cfc\0\u26b7\0\u1d66\0\u26ec\0\u2721\0\u2756\0\u278b\0\u27c0"+
    "\0\u27f5\0\u282a\0\u285f\0\u04c3\0\u2894\0\u28c9\0\u28fe\0\u2933"+
    "\0\u2968\0\u299d\0\u04c3\0\u29d2\0\u2a07\0\u04c3\0\u2a3c\0\u2a71"+
    "\0\u2aa6\0\u2adb\0\u2b10\0\u04c3\0\u2b45\0\u2b7a\0\u2baf\0\u2be4"+
    "\0\u04c3\0\u2c19\0\u2c4e\0\u2c83\0\u2cb8\0\u2ced\0\u2d22\0\u2d57"+
    "\0\u2d8c\0\u04c3\0\u04c3\0\u2dc1\0\u2df6\0\u2e2b\0\u04c3\0\u2e60"+
    "\0\u2e95\0\u2618\0\u04c3\0\u04c3\0\u2eca\0\u2eff\0\u2f34\0\u2f69"+
    "\0\u2f9e\0\u2fd3\0\u3008\0\u04c3\0\u303d\0\u3072\0\u30a7\0\u30dc"+
    "\0\u04c3\0\u3111\0\u3146\0\u317b\0\u31b0\0\u31e5\0\u04c3\0\u321a"+
    "\0\u324f\0\u3284\0\u04c3\0\u32b9\0\u32ee\0\u3323\0\u3358\0\u04c3"+
    "\0\u338d\0\u33c2\0\u04c3\0\u04c3\0\u33f7\0\u04c3\0\u342c\0\u3461"+
    "\0\u04c3\0\u04c3\0\u3496\0\u34cb\0\u3500\0\u3535\0\u356a\0\u359f"+
    "\0\u35d4\0\u3609\0\u04c3\0\u363e\0\u3673\0\u36a8\0\u36dd\0\u3712"+
    "\0\u04c3\0\u3747\0\u04c3\0\u377c\0\u37b1\0\u37e6\0\u04c3\0\u04c3"+
    "\0\u04c3\0\u381b\0\u3850\0\u3885\0\u38ba\0\u38ef\0\u04c3\0\u04c3"+
    "\0\u04c3\0\u3924\0\u3959\0\u04c3\0\u398e\0\u39c3\0\u04c3\0\u39f8"+
    "\0\u3a2d\0\u3a62\0\u3a97\0\u3acc\0\u3b01\0\u3b36\0\u04c3\0\u3b6b"+
    "\0\u3ba0\0\u3bd5\0\u3c0a\0\u3c3f\0\u04c3\0\u04c3\0\u04c3\0\u3c74"+
    "\0\u04c3\0\u04c3\0\u04c3\0\u3ca9\0\u3cde\0\u3d13\0\u3d48\0\u04c3"+
    "\0\u3d7d\0\u3db2\0\u3de7\0\u3e1c\0\u04c3\0\u3e51\0\u3e86\0\u04c3"+
    "\0\u04c3\0\u04c3\0\u04c3\0\u04c3\0\u04c3";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[421];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\30\1\31\4\32\57\30\1\33\1\34\2\35\1\36"+
    "\1\35\1\33\1\37\2\33\12\40\14\33\17\40\6\33"+
    "\2\41\2\42\1\43\1\42\1\41\1\44\21\41\1\45"+
    "\33\41\3\33\1\0\1\46\25\33\1\47\32\33\3\50"+
    "\1\0\1\51\60\50\2\52\2\53\1\54\1\52\1\55"+
    "\1\52\1\56\14\52\1\57\1\60\1\61\1\56\2\52"+
    "\1\62\1\63\1\64\1\65\26\52\2\66\2\53\5\66"+
    "\1\67\12\70\14\66\17\70\6\66\2\71\2\53\2\71"+
    "\1\72\17\71\1\73\10\71\1\74\25\71\2\75\2\53"+
    "\1\76\4\75\1\77\1\100\1\101\1\102\1\103\1\75"+
    "\1\104\1\75\1\105\1\106\2\75\1\107\12\75\1\110"+
    "\1\111\1\75\1\112\1\113\1\114\1\115\1\116\5\75"+
    "\1\117\1\75\1\120\1\121\1\122\5\75\2\53\1\76"+
    "\60\75\2\123\2\53\1\124\5\123\12\125\14\123\17\125"+
    "\6\123\2\126\2\53\1\127\5\126\12\130\14\126\17\130"+
    "\4\126\1\131\1\126\2\132\2\53\5\132\1\133\13\132"+
    "\1\107\37\132\1\134\1\135\4\136\57\134\2\137\2\53"+
    "\1\140\4\137\1\141\12\142\1\137\1\143\12\137\17\142"+
    "\4\137\1\144\1\137\2\145\2\53\1\146\7\145\1\147"+
    "\2\145\1\150\45\145\2\151\2\152\1\153\5\151\12\154"+
    "\14\151\17\154\4\151\1\155\1\156\2\41\2\157\1\160"+
    "\1\157\1\41\1\161\1\41\1\162\13\41\1\163\3\41"+
    "\1\164\33\41\2\165\2\152\1\166\1\165\1\167\1\165"+
    "\1\170\14\165\1\171\1\172\1\173\1\170\2\165\1\174"+
    "\1\175\1\176\1\177\26\165\3\200\1\0\5\200\1\201"+
    "\12\202\1\200\1\203\12\200\17\202\6\200\2\204\2\152"+
    "\2\204\1\205\17\204\1\206\10\204\1\207\25\204\2\210"+
    "\4\211\17\210\1\212\37\210\2\213\4\214\3\213\1\215"+
    "\13\213\1\216\37\213\66\0\1\217\65\0\4\32\60\0"+
    "\1\220\65\0\4\35\61\0\2\35\1\36\1\35\1\0"+
    "\1\221\64\0\1\222\1\223\66\0\13\40\13\0\23\40"+
    "\4\0\4\42\61\0\2\42\1\43\1\42\1\0\1\224"+
    "\64\0\1\225\1\226\60\0\1\46\64\0\1\51\62\0"+
    "\2\53\65\0\1\54\60\0\2\52\2\0\61\52\2\227"+
    "\2\0\2\227\1\230\17\227\1\231\36\227\12\0\13\70"+
    "\13\0\23\70\2\0\2\71\2\0\61\71\2\232\2\0"+
    "\2\232\1\233\17\232\1\234\36\232\4\0\1\76\73\0"+
    "\1\235\26\0\1\236\11\0\1\237\26\0\1\240\67\0"+
    "\1\241\33\0\1\242\25\0\1\243\25\0\1\244\32\0"+
    "\1\245\33\0\1\246\61\0\1\247\3\0\1\250\27\0"+
    "\1\251\70\0\1\252\2\0\1\253\1\254\23\0\1\255"+
    "\2\0\1\256\27\0\1\257\23\0\1\260\11\0\1\261"+
    "\33\0\1\262\24\0\1\263\57\0\1\264\40\0\1\265"+
    "\62\0\1\266\117\0\1\267\6\0\1\270\64\0\1\271"+
    "\56\0\1\272\64\0\1\273\77\0\1\274\6\0\1\124"+
    "\72\0\13\125\13\0\23\125\6\0\1\127\72\0\13\130"+
    "\13\0\23\130\13\0\1\275\1\276\2\0\1\277\51\0"+
    "\4\136\63\0\1\140\72\0\13\142\13\0\23\142\6\0"+
    "\1\146\130\0\1\300\35\0\1\301\45\0\2\152\65\0"+
    "\1\153\72\0\13\154\13\0\23\154\4\0\4\157\61\0"+
    "\2\157\1\160\1\157\1\0\1\302\64\0\1\303\1\304"+
    "\66\0\12\305\14\0\17\305\12\0\1\166\60\0\2\165"+
    "\2\0\61\165\12\0\12\306\14\0\17\306\6\0\2\307"+
    "\2\0\2\307\1\310\17\307\1\311\36\307\12\0\13\202"+
    "\13\0\23\202\2\0\2\204\2\0\61\204\2\312\2\0"+
    "\2\312\1\313\17\312\1\314\36\312\2\0\4\211\61\0"+
    "\4\214\66\0\1\222\55\0\3\222\1\0\61\222\10\315"+
    "\1\316\54\315\7\0\1\225\55\0\3\225\1\0\61\225"+
    "\10\317\1\320\54\317\2\227\2\0\2\227\1\230\17\227"+
    "\1\321\36\227\2\232\2\0\2\232\1\233\17\232\1\322"+
    "\36\232\12\0\1\323\1\0\1\324\23\0\1\325\67\0"+
    "\1\326\34\0\1\327\65\0\1\330\117\0\1\331\60\0"+
    "\1\332\40\0\1\333\61\0\1\334\63\0\1\335\64\0"+
    "\1\336\6\0\1\337\54\0\1\340\113\0\1\341\36\0"+
    "\1\342\73\0\1\343\103\0\1\344\44\0\1\345\106\0"+
    "\1\346\42\0\1\347\64\0\1\350\64\0\1\351\55\0"+
    "\1\352\112\0\1\353\73\0\1\354\31\0\1\355\117\0"+
    "\1\356\27\0\1\357\71\0\1\360\66\0\1\361\60\0"+
    "\1\362\4\0\1\363\54\0\1\364\64\0\1\365\121\0"+
    "\1\366\30\0\1\367\67\0\1\370\114\0\1\371\40\0"+
    "\1\372\51\0\1\303\55\0\3\303\1\0\61\303\10\373"+
    "\1\374\54\373\11\0\1\41\13\305\13\0\23\305\13\0"+
    "\1\375\13\306\13\0\23\306\2\0\2\307\2\0\2\307"+
    "\1\310\17\307\1\376\36\307\2\312\2\0\2\312\1\313"+
    "\17\312\1\377\36\312\10\315\1\u0100\63\315\1\u0101\1\u0100"+
    "\54\315\10\317\1\u0102\63\317\1\u0103\1\u0102\54\317\14\0"+
    "\1\u0104\65\0\1\u0105\34\0\1\u0106\34\0\1\u0107\64\0"+
    "\1\u0108\60\0\1\u0109\114\0\1\u010a\40\0\1\u010b\57\0"+
    "\1\u010c\63\0\1\u010d\3\0\1\u010e\17\0\1\u010f\41\0"+
    "\1\u0110\70\0\1\u0111\103\0\1\u0112\46\0\1\u0113\105\0"+
    "\1\u0114\35\0\1\u0115\65\0\1\u0116\115\0\1\u0117\33\0"+
    "\1\u0118\110\0\1\u0119\64\0\1\u011a\3\0\1\u011b\67\0"+
    "\1\u011c\27\0\1\u011d\1\u011e\63\0\1\u011f\65\0\1\u0120"+
    "\126\0\1\u0121\30\0\1\u0122\63\0\1\u0123\111\0\1\u0124"+
    "\56\0\1\u0125\43\0\1\u0126\105\0\1\u0127\42\0\1\u0128"+
    "\63\0\1\u0129\63\0\1\u012a\64\0\1\u012b\62\0\1\u012c"+
    "\64\0\1\u012d\71\0\1\u012e\62\0\1\u012f\110\0\1\u0130"+
    "\23\0\10\373\1\u0131\63\373\1\u0132\1\u0131\54\373\7\315"+
    "\1\u0133\1\u0100\54\315\7\317\1\u0134\1\u0102\54\317\14\0"+
    "\1\u0135\124\0\1\u0136\60\0\1\u0137\62\0\1\u0138\33\0"+
    "\1\u0139\117\0\1\u013a\27\0\1\u013b\66\0\1\u013c\120\0"+
    "\1\u013d\34\0\1\u013e\65\0\1\u013f\55\0\1\u0140\73\0"+
    "\1\u0141\56\0\1\u0142\120\0\1\u0143\64\0\1\u0144\56\0"+
    "\1\u0145\44\0\1\u0146\103\0\1\u0147\100\0\1\u0148\24\0"+
    "\1\u0149\114\0\1\u014a\34\0\1\u014b\64\0\1\u014c\107\0"+
    "\1\u014d\36\0\1\u014e\66\0\1\u014f\124\0\1\u0150\26\0"+
    "\1\u0151\63\0\1\u0152\107\0\1\u0153\43\0\1\u0154\111\0"+
    "\1\u0155\34\0\1\u0156\64\0\1\u0157\61\0\1\275\6\0"+
    "\1\u0158\61\0\1\u0159\47\0\7\373\1\u015a\1\u0131\54\373"+
    "\51\0\1\u015b\30\0\1\u015c\70\0\1\u015d\110\0\1\u015e"+
    "\61\0\1\u015f\37\0\1\u0160\61\0\1\u0161\122\0\1\u0162"+
    "\36\0\1\u0163\60\0\1\u0164\113\0\1\u0165\31\0\1\u0166"+
    "\64\0\1\u0167\73\0\1\u0168\56\0\1\u0169\66\0\1\u016a"+
    "\111\0\1\u016b\71\0\1\u016c\36\0\1\u016d\113\0\1\u016e"+
    "\65\0\1\u016f\53\0\1\u0170\41\0\1\u0171\114\0\1\u0172"+
    "\67\0\1\u0173\30\0\1\u0174\61\0\1\275\74\0\1\u0175"+
    "\113\0\1\u0176\64\0\1\u0177\57\0\1\u0178\36\0\1\u0179"+
    "\64\0\1\u017a\107\0\1\u017b\70\0\1\u017c\36\0\1\u017d"+
    "\107\0\1\u017e\64\0\1\u017f\41\0\1\u0180\66\0\1\u0181"+
    "\104\0\1\u0182\65\0\1\u0183\71\0\1\u0184\40\0\1\u0185"+
    "\112\0\1\u0186\31\0\1\u0187\110\0\1\u0188\74\0\1\u0189"+
    "\35\0\1\u0157\60\0\1\u018a\61\0\1\u018b\72\0\1\u018c"+
    "\115\0\1\u018d\27\0\1\u018e\62\0\1\u018f\72\0\1\u0190"+
    "\57\0\1\u0191\111\0\1\u0192\77\0\1\u0193\26\0\1\u0194"+
    "\64\0\1\u0195\60\0\1\u0196\122\0\1\u0197\66\0\1\u0198"+
    "\26\0\1\u0199\111\0\1\u019a\37\0\1\u019b\63\0\1\u019c"+
    "\121\0\1\u019d\67\0\1\u019e\27\0\1\u019f\107\0\1\u01a0"+
    "\40\0\1\u01a1\64\0\1\u01a2\64\0\1\u01a3\64\0\1\u01a4"+
    "\121\0\1\u01a5\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[16059];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\27\0\1\11\2\1\1\11\5\1\1\11\3\1\1\11"+
    "\1\1\2\11\1\1\1\11\3\1\2\11\1\1\7\11"+
    "\1\1\1\11\2\1\2\11\1\1\1\11\7\1\1\11"+
    "\13\1\1\11\2\1\1\11\2\1\4\11\2\1\1\11"+
    "\1\1\1\11\1\1\3\11\3\1\1\11\3\1\2\11"+
    "\3\1\1\11\1\1\2\11\2\1\1\11\2\1\7\11"+
    "\1\1\2\11\2\1\2\11\1\1\2\11\1\1\4\11"+
    "\1\0\1\1\2\0\1\1\3\0\1\11\2\0\1\11"+
    "\40\0\1\11\5\0\1\1\5\0\1\11\2\0\1\11"+
    "\4\0\2\1\1\0\1\1\6\0\1\1\12\0\1\1"+
    "\26\0\1\11\2\1\1\0\1\1\1\0\2\1\7\0"+
    "\1\11\6\0\1\11\2\0\1\11\5\0\1\11\4\0"+
    "\1\11\10\0\2\11\3\0\1\11\2\0\1\1\2\11"+
    "\7\0\1\11\4\0\1\11\5\0\1\11\3\0\1\11"+
    "\4\0\1\11\2\0\2\11\1\0\1\11\2\0\2\11"+
    "\10\0\1\11\5\0\1\11\1\0\1\11\3\0\3\11"+
    "\5\0\3\11\2\0\1\11\2\0\1\11\7\0\1\11"+
    "\5\0\3\11\1\0\3\11\4\0\1\11\4\0\1\11"+
    "\2\0\6\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[421];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private int braceCounter = 0;


  _JFlexLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  _JFlexLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1764) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  // For Demetra compatibility
  public void reset(CharSequence buffer, int initialState){
    reset(buffer, 0, buffer.length(), initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = zzLexicalState;


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 23: 
          { yybegin(IDENTIFIER_REGEXP); return JFlexElementTypes.REGEXP_RIGHT_BRACE;
          }
        case 138: break;
        case 109: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.YYEOF_KEYWORD;
          }
        case 139: break;
        case 21: 
          { yybegin(IDENTIFIER_REGEXP); return JFlexElementTypes.REGEXP_RIGHT_PARENTHESIS;
          }
        case 140: break;
        case 87: 
          { yybegin(RULE); return JFlexElementTypes.COMMENT;
          }
        case 141: break;
        case 19: 
          { yybegin(IDENTIFIER_REGEXP); return JFlexElementTypes.REGEXP_OR;
          }
        case 142: break;
        case 25: 
          { yybegin(IDENTIFIER_REGEXP_CLASS); return JFlexElementTypes.REGEXP_CLASS_SYMBOL;
          }
        case 143: break;
        case 121: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.NOTUNIX_KEYWORD;
          }
        case 144: break;
        case 59: 
          { yybegin(STATE); return JFlexElementTypes.STATE_RIGHT_ANGLE_BRACKET;
          }
        case 145: break;
        case 123: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.UNICODE_KEYWORD;
          }
        case 146: break;
        case 64: 
          { yybegin(ACTION_REGEXP); return JFlexElementTypes.REGEXP_PREFIX;
          }
        case 147: break;
        case 66: 
          { yybegin(ACTION_REGEXP); return JFlexElementTypes.REGEXP_OR;
          }
        case 148: break;
        case 88: 
          { yybegin(ACTION_REGEXP); return JFlexElementTypes.REGEXP_STRING_LITERAL;
          }
        case 149: break;
        case 90: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.INT_KEYWORD;
          }
        case 150: break;
        case 43: 
          { yybegin(OPT_EXCEPTION); return JFlexElementTypes.BAD_CHARACTER;
          }
        case 151: break;
        case 131: 
          { yybegin(OPT_PARAM); return JFlexElementTypes.SCANERROR_KEYWORD;
          }
        case 152: break;
        case 133: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.IGNORECASE_KEYWORD;
          }
        case 153: break;
        case 36: 
          { yybegin(OPT_PARAMS); return JFlexElementTypes.BAD_CHARACTER;
          }
        case 154: break;
        case 81: 
          { yybegin(LEXICAL_RULES); return JFlexElementTypes.SECTION_SIGN;
          }
        case 155: break;
        case 80: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.SECTION_SIGN;
          }
        case 156: break;
        case 77: 
          { yybegin(ACTION_JAVA_CODE); return JFlexElementTypes.JAVA_CODE;
          }
        case 157: break;
        case 98: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.CHAR_KEYWORD;
          }
        case 158: break;
        case 65: 
          { yybegin(ACTION_REGEXP_CLASS); return JFlexElementTypes.REGEXP_LEFT_BRACKET;
          }
        case 159: break;
        case 129: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.CUPDEBUG_KEYWORD;
          }
        case 160: break;
        case 17: 
          { yybegin(IDENTIFIER_REGEXP); return JFlexElementTypes.REGEXP_PREFIX;
          }
        case 161: break;
        case 79: 
          { braceCounter++; yybegin(ACTION_JAVA_CODE); return JFlexElementTypes.JAVA_CODE;
          }
        case 162: break;
        case 2: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.BAD_CHARACTER;
          }
        case 163: break;
        case 127: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.ABSTRACT_KEYWORD;
          }
        case 164: break;
        case 100: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes._7BIT_KEYWORD;
          }
        case 165: break;
        case 92: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.CUP_KEYWORD;
          }
        case 166: break;
        case 45: 
          { yybegin(OPT_EXCEPTION); return JFlexElementTypes.OPTION_RIGHT_BRACE;
          }
        case 167: break;
        case 116: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.PUBLIC_KEYWORD;
          }
        case 168: break;
        case 75: 
          { yybegin(RULE); return JFlexElementTypes.BAD_CHARACTER;
          }
        case 169: break;
        case 70: 
          { yybegin(ACTION_REGEXP); return JFlexElementTypes.REGEXP_RIGHT_BRACE;
          }
        case 170: break;
        case 18: 
          { yybegin(IDENTIFIER_REGEXP_CLASS); return JFlexElementTypes.REGEXP_LEFT_BRACKET;
          }
        case 171: break;
        case 53: 
          { yybegin(STATE); return JFlexElementTypes.STATE_REF;
          }
        case 172: break;
        case 132: 
          { yybegin(OPT_PARAMS); return JFlexElementTypes.IMPLEMENTS_KEYWORD;
          }
        case 173: break;
        case 118: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.INTEGER_KEYWORD;
          }
        case 174: break;
        case 135: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.STANDALONE_KEYWORD;
          }
        case 175: break;
        case 113: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.COLUMN_KEYWORD;
          }
        case 176: break;
        case 1: 
          { yybegin(YYINITIAL); return JFlexElementTypes.JAVA_CODE;
          }
        case 177: break;
        case 97: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.LINE_KEYWORD;
          }
        case 178: break;
        case 35: 
          { yybegin(OPT_PARAM); return JFlexElementTypes.OPTION_PARAMETER;
          }
        case 179: break;
        case 122: 
          { yybegin(OPT_PARAM); return JFlexElementTypes.EXTENDS_KEYWORD;
          }
        case 180: break;
        case 57: 
          { yybegin(LEXICAL_RULES); return JFlexElementTypes.RIGHT_BRACE;
          }
        case 181: break;
        case 112: 
          { yybegin(OPT_CODE); return JFlexElementTypes.EOFVAL_KEYWORD;
          }
        case 182: break;
        case 106: 
          { yybegin(OPT_PARAMS); return JFlexElementTypes.STATE_KEYWORD;
          }
        case 183: break;
        case 89: 
          { yybegin(ACTION_REGEXP_CLASS); return JFlexElementTypes.REGEXP_STRING_LITERAL;
          }
        case 184: break;
        case 114: 
          { yybegin(OPT_PARAM); return JFlexElementTypes.CUPSYM_KEYWORD;
          }
        case 185: break;
        case 84: 
          { yybegin(IDENTIFIER_REGEXP); return JFlexElementTypes.REGEXP_STRING_LITERAL;
          }
        case 186: break;
        case 91: 
          { yybegin(OPT_CODE); return JFlexElementTypes.EOF_KEYWORD;
          }
        case 187: break;
        case 42: 
          { yybegin(OPT_JAVA_CODE); return JFlexElementTypes.JAVA_CODE;
          }
        case 188: break;
        case 46: 
          { yybegin(OPT_EXCEPTION); return JFlexElementTypes.OPTION_PARAMETER;
          }
        case 189: break;
        case 115: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.SWITCH_KEYWORD;
          }
        case 190: break;
        case 111: 
          { yybegin(OPT_BOOLEAN); return JFlexElementTypes.FALSE_KEYWORD;
          }
        case 191: break;
        case 20: 
          { yybegin(IDENTIFIER_REGEXP); return JFlexElementTypes.REGEXP_LEFT_PARENTHESIS;
          }
        case 192: break;
        case 27: 
          { yybegin(OPT_ERROR); return JFlexElementTypes.BAD_CHARACTER;
          }
        case 193: break;
        case 5: 
          { yybegin(IDENTIFIER); return JFlexElementTypes.MACROS;
          }
        case 194: break;
        case 16: 
          { yybegin(IDENTIFIER_REGEXP_IDENTIFIER); return JFlexElementTypes.REGEXP_LEFT_BRACE;
          }
        case 195: break;
        case 28: 
          { yybegin(OPT_ERROR); return JFlexElementTypes.OPTION_WHITE_SPACE;
          }
        case 196: break;
        case 12: 
          { yybegin(IDENTIFIER_REGEXP_LITERAL); return JFlexElementTypes.WHITE_SPACE;
          }
        case 197: break;
        case 14: 
          { yybegin(IDENTIFIER_REGEXP); return JFlexElementTypes.REGEXP_WHITE_SPACE;
          }
        case 198: break;
        case 54: 
          { yybegin(STATE); return JFlexElementTypes.STATE_COMMA;
          }
        case 199: break;
        case 10: 
          { yybegin(IDENTIFIER_REGEXP_LITERAL); return JFlexElementTypes.EQ;
          }
        case 200: break;
        case 103: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.TABLE_KEYWORD;
          }
        case 201: break;
        case 94: 
          { yybegin(OPT_CODE); return JFlexElementTypes.INIT_KEYWORD;
          }
        case 202: break;
        case 86: 
          { yybegin(OPTIONS_AND_DECLARATIONS); yypushback(yylength());
          }
        case 203: break;
        case 85: 
          { yybegin(IDENTIFIER_REGEXP_CLASS); return JFlexElementTypes.REGEXP_STRING_LITERAL;
          }
        case 204: break;
        case 49: 
          { yybegin(OPT_BOOLEAN); return JFlexElementTypes.BAD_CHARACTER;
          }
        case 205: break;
        case 39: 
          { yybegin(OPT_PARAMS); return JFlexElementTypes.OPTION_COMMA;
          }
        case 206: break;
        case 101: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes._8BIT_KEYWORD;
          }
        case 207: break;
        case 52: 
          { yybegin(STATE); return JFlexElementTypes.WHITE_SPACE;
          }
        case 208: break;
        case 51: 
          { yybegin(STATE); return JFlexElementTypes.BAD_CHARACTER;
          }
        case 209: break;
        case 32: 
          { yybegin(OPT_PARAMS); return JFlexElementTypes.X_KEYWORD;
          }
        case 210: break;
        case 93: 
          { yybegin(ACTION_REGEXP_IDENTIFIER); yypushback(yylength());
          }
        case 211: break;
        case 104: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.FINAL_KEYWORD;
          }
        case 212: break;
        case 82: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.COMMENT;
          }
        case 213: break;
        case 96: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.FULL_KEYWORD;
          }
        case 214: break;
        case 78: 
          { braceCounter--; if (braceCounter < 0) {yybegin(RULE); return JFlexElementTypes.RIGHT_BRACE; } else { yybegin(ACTION_JAVA_CODE); return JFlexElementTypes.JAVA_CODE; }
          }
        case 215: break;
        case 83: 
          { yybegin(LEXICAL_RULES); return JFlexElementTypes.COMMENT;
          }
        case 216: break;
        case 61: 
          { yybegin(ACTION_REGEXP); return JFlexElementTypes.WHITE_SPACE;
          }
        case 217: break;
        case 50: 
          { yybegin(OPT_BOOLEAN); return JFlexElementTypes.OPTION_WHITE_SPACE;
          }
        case 218: break;
        case 55: 
          { yybegin(RULE); return JFlexElementTypes.STATE_LEFT_ANGLE_BRACKET;
          }
        case 219: break;
        case 68: 
          { yybegin(ACTION_REGEXP); return JFlexElementTypes.REGEXP_RIGHT_PARENTHESIS;
          }
        case 220: break;
        case 74: 
          { yybegin(ACTION_REGEXP); return JFlexElementTypes.REGEXP_RIGHT_BRACKET;
          }
        case 221: break;
        case 60: 
          { yybegin(ACTION_REGEXP); return JFlexElementTypes.REGEXP_SYMBOL;
          }
        case 222: break;
        case 76: 
          { yybegin(ACTION); return JFlexElementTypes.WHITE_SPACE;
          }
        case 223: break;
        case 69: 
          { yybegin(ACTION_REGEXP); return JFlexElementTypes.BAD_CHARACTER;
          }
        case 224: break;
        case 29: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.OPTION_RIGHT_BRACE;
          }
        case 225: break;
        case 107: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.DEBUG_KEYWORD;
          }
        case 226: break;
        case 37: 
          { yybegin(OPT_PARAMS); return JFlexElementTypes.OPTION_WHITE_SPACE;
          }
        case 227: break;
        case 44: 
          { yybegin(OPT_EXCEPTION); return JFlexElementTypes.OPTION_WHITE_SPACE;
          }
        case 228: break;
        case 24: 
          { yybegin(IDENTIFIER_REGEXP_IDENTIFIER); return JFlexElementTypes.REGEXP_MACROS_REF;
          }
        case 229: break;
        case 137: 
          { yybegin(OPT_EXCEPTION); return JFlexElementTypes.YYLEXTHROW_KEYWORD;
          }
        case 230: break;
        case 126: 
          { yybegin(OPT_PARAM); return JFlexElementTypes.FUNCTION_KEYWORD;
          }
        case 231: break;
        case 58: 
          { yybegin(RULE); return JFlexElementTypes.LEFT_BRACE;
          }
        case 232: break;
        case 136: 
          { yybegin(OPT_PARAM); return JFlexElementTypes.BUFFERSIZE_KEYWORD;
          }
        case 233: break;
        case 134: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.APIPRIVATE_KEYWORD;
          }
        case 234: break;
        case 124: 
          { yybegin(OPT_EXCEPTION); return JFlexElementTypes.EOFTHROW_KEYWORD;
          }
        case 235: break;
        case 62: 
          { yybegin(ACTION_REGEXP); return JFlexElementTypes.REGEXP_POSTFIX;
          }
        case 236: break;
        case 119: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.INTWRAP_KEYWORD;
          }
        case 237: break;
        case 120: 
          { yybegin(OPT_PARAM); return JFlexElementTypes.INCLUDE_KEYWORD;
          }
        case 238: break;
        case 72: 
          { yybegin(ACTION_REGEXP_IDENTIFIER); return JFlexElementTypes.REGEXP_LEFT_BRACE;
          }
        case 239: break;
        case 48: 
          { yybegin(OPT_EXCEPTION); return JFlexElementTypes.OPTION_COMMA;
          }
        case 240: break;
        case 26: 
          { yybegin(IDENTIFIER_REGEXP); return JFlexElementTypes.REGEXP_RIGHT_BRACKET;
          }
        case 241: break;
        case 30: 
          { yybegin(OPT_JAVA_CODE); return JFlexElementTypes.OPTION_LEFT_BRACE;
          }
        case 242: break;
        case 11: 
          { yybegin(IDENTIFIER_REGEXP); yypushback(yylength());
          }
        case 243: break;
        case 105: 
          { yybegin(OPT_PARAM); return JFlexElementTypes.CLASS_KEYWORD;
          }
        case 244: break;
        case 13: 
          { yybegin(IDENTIFIER_REGEXP); return JFlexElementTypes.REGEXP_SYMBOL;
          }
        case 245: break;
        case 22: 
          { yybegin(IDENTIFIER_REGEXP); return JFlexElementTypes.BAD_CHARACTER;
          }
        case 246: break;
        case 8: 
          { yybegin(STATE); return JFlexElementTypes.STATE_LEFT_ANGLE_BRACKET;
          }
        case 247: break;
        case 34: 
          { yybegin(OPT_PARAM); return JFlexElementTypes.OPTION_WHITE_SPACE;
          }
        case 248: break;
        case 63: 
          { braceCounter = 0; yybegin(ACTION_JAVA_CODE); return JFlexElementTypes.LEFT_BRACE;
          }
        case 249: break;
        case 56: 
          { yybegin(RULE); return JFlexElementTypes.WHITE_SPACE;
          }
        case 250: break;
        case 110: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes._16BIT_KEYWORD;
          }
        case 251: break;
        case 102: 
          { yybegin(OPT_BOOLEAN); return JFlexElementTypes.TRUE_KEYWORD;
          }
        case 252: break;
        case 73: 
          { yybegin(ACTION_REGEXP_CLASS); return JFlexElementTypes.REGEXP_CLASS_SYMBOL;
          }
        case 253: break;
        case 108: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.BYACC_KEYWORD;
          }
        case 254: break;
        case 7: 
          { yybegin(LEXICAL_RULES); return JFlexElementTypes.WHITE_SPACE;
          }
        case 255: break;
        case 125: 
          { yybegin(OPT_BOOLEAN); return JFlexElementTypes.EOFCLOSE_KEYWORD;
          }
        case 256: break;
        case 31: 
          { yybegin(OPT_PARAMS); return JFlexElementTypes.S_KEYWORD;
          }
        case 257: break;
        case 95: 
          { yybegin(OPT_PARAM); return JFlexElementTypes.TYPE_KEYWORD;
          }
        case 258: break;
        case 99: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.PACK_KEYWORD;
          }
        case 259: break;
        case 33: 
          { yybegin(OPT_PARAM); return JFlexElementTypes.BAD_CHARACTER;
          }
        case 260: break;
        case 9: 
          { yybegin(IDENTIFIER); return JFlexElementTypes.WHITE_SPACE;
          }
        case 261: break;
        case 38: 
          { yybegin(OPT_PARAMS); return JFlexElementTypes.OPTION_PARAMETER;
          }
        case 262: break;
        case 3: 
          { yybegin(OPTION); return JFlexElementTypes.OPTION_SIGN;
          }
        case 263: break;
        case 15: 
          { yybegin(IDENTIFIER_REGEXP); return JFlexElementTypes.REGEXP_POSTFIX;
          }
        case 264: break;
        case 128: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.CASELESS_KEYWORD;
          }
        case 265: break;
        case 6: 
          { yybegin(ACTION_REGEXP); yypushback(yylength());
          }
        case 266: break;
        case 40: 
          { yybegin(OPT_CODE); return JFlexElementTypes.BAD_CHARACTER;
          }
        case 267: break;
        case 67: 
          { yybegin(ACTION_REGEXP); return JFlexElementTypes.REGEXP_LEFT_PARENTHESIS;
          }
        case 268: break;
        case 41: 
          { yybegin(OPT_CODE); return JFlexElementTypes.OPTION_RIGHT_BRACE;
          }
        case 269: break;
        case 4: 
          { yybegin(OPTIONS_AND_DECLARATIONS); return JFlexElementTypes.WHITE_SPACE;
          }
        case 270: break;
        case 71: 
          { yybegin(ACTION_REGEXP_IDENTIFIER); return JFlexElementTypes.REGEXP_MACROS_REF;
          }
        case 271: break;
        case 47: 
          { yybegin(OPT_EXCEPTION); return JFlexElementTypes.OPTION_LEFT_BRACE;
          }
        case 272: break;
        case 130: 
          { yybegin(OPT_EXCEPTION); return JFlexElementTypes.INITTHROW_KEYWORD;
          }
        case 273: break;
        case 117: 
          { yybegin(OPT_PARAMS); return JFlexElementTypes.XSTATE_KEYWORD;
          }
        case 274: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
